use crate::storage::qdrant::{MemoryPoint, RealmPoint};

/// Write a MEMEX8.md file to a project directory containing the most important memories.
pub async fn write_memex8_md(
    project_dir: &str,
    memories: &[MemoryPoint],
    realms: &[RealmPoint],
    max_memories: usize,
) -> anyhow::Result<()> {
    let path = std::path::Path::new(project_dir).join("MEMEX8.md");

    let mut md = String::new();
    md.push_str("# MEMEX8 — Memory Context\n");
    md.push_str("<!-- Auto-generated by memex8. Do not edit. Last updated: ");
    md.push_str(&chrono::Utc::now().to_rfc3339());
    md.push_str(" -->\n\n");

    // Active Realms section
    md.push_str("## Active Realms\n");
    for realm in realms {
        md.push_str(&format!(
            "- **{}** ({} memories)",
            realm.name, realm.memory_count
        ));
        if let Some(desc) = &realm.description {
            md.push_str(&format!(" — {}", desc));
        }
        md.push('\n');
    }
    md.push('\n');

    // Top memories by importance
    md.push_str("## Key Memories\n\n");
    let mut sorted: Vec<&MemoryPoint> = memories.iter().collect();
    sorted.sort_by(|a, b| {
        b.importance
            .partial_cmp(&a.importance)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    for memory in sorted.iter().take(max_memories) {
        if let Some(heading) = &memory.heading {
            md.push_str(&format!("### [{}] {}\n", memory.realm_name, heading));
        } else {
            md.push_str(&format!("### [{}]\n", memory.realm_name));
        }

        // Truncate content to first ~200 chars
        let preview: String = memory.content.chars().take(200).collect();
        md.push_str(&format!("> {}...\n\n", preview));
    }

    md.push_str("---\n");
    md.push_str("*Full memory access: `memex8 search \"<query>\"` or http://localhost:8080*\n");

    std::fs::write(&path, md)?;
    tracing::info!("Wrote MEMEX8.md to {}", path.display());
    Ok(())
}

/// Append a slumber digest entry to the configured memex8.md file.
/// Preserves any existing header ("how to use" section) and appends a new dated entry.
/// Keeps only the most recent `max_log_entries` entries and skips duplicate entries
/// (same date + identical stats) from rapid re-runs.
pub async fn write_digest_md(
    config: &crate::config::DigestMdConfig,
    memories: &[MemoryPoint],
    _realms: &[RealmPoint],
    report: &crate::engine::slumber::SlumberReport,
) -> anyhow::Result<usize> {
    if !config.enabled {
        return Ok(0);
    }

    // Expand ~ to HOME
    let path_str = config
        .path
        .replace("~", &std::env::var("HOME").unwrap_or_default());
    let path = std::path::Path::new(&path_str);

    // Create parent dir if needed
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let header = r#"# memex8 — Memory Digest

> Auto-generated by memex8 slumber. Do not edit manually.
> **How to use**: Search `memex8_recall` for wake-up context, `memex8_search <query>` for topics,
> `memex8_remember <fact>` to store new memories, `memex8_forget <id>` to delete.

---

"#;

    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let timestamp = chrono::Utc::now().to_rfc3339();

    // Build this run's entry
    let mut entry = format!("## {}\n\n**Slumber cycle** at {}\n\n", date, timestamp);

    // Summarize what slumber did
    if report.memories_scanned > 0 {
        entry.push_str(&format!(
            "- 📊 Scanned {} memories\n",
            report.memories_scanned
        ));
    }
    if report.deduplicated > 0 {
        entry.push_str(&format!(
            "- 🔀 Deduplicated {} pairs\n",
            report.deduplicated
        ));
    }
    if report.quantized > 0 {
        entry.push_str(&format!(
            "- 🗜️  ScalarQuant compressed {} vectors\n",
            report.quantized
        ));
    }
    if report.realms_updated > 0 {
        entry.push_str(&format!("- 🌐 Updated {} realms\n", report.realms_updated));
    }
    if report.realms_renamed > 0 {
        entry.push_str(&format!("- ✏️  Renamed {} realms\n", report.realms_renamed));
    }
    if report.memories_consolidated > 0 {
        entry.push_str(&format!(
            "- 🧠 LLM consolidated {} memories\n",
            report.memories_consolidated
        ));
    }
    if report.flagged_for_prune > 0 {
        entry.push_str(&format!(
            "- 🗑️  Flagged {} for pruning\n",
            report.flagged_for_prune
        ));
    }
    if report.index_optimized > 0 {
        entry.push_str(&format!(
            "- ⚡ Optimized Qdrant index ({})\n",
            report.index_optimized
        ));
    }
    if report.realms_pruned > 0 {
        entry.push_str(&format!("- 🧹 Pruned {} empty realms\n", report.realms_pruned));
    }

    // Top important memories this run — use config.max_memories, not hardcoded 5
    let top_n = if config.max_memories > 0 {
        config.max_memories as usize
    } else {
        5
    };
    if !memories.is_empty() {
        entry.push_str("\n**Top memories by importance:**\n\n");
        let mut sorted: Vec<&MemoryPoint> = memories.iter().collect();
        sorted.sort_by(|a, b| {
            b.importance
                .partial_cmp(&a.importance)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        for memory in sorted.iter().take(top_n) {
            let preview: String = memory.content.chars().take(120).collect();
            entry.push_str(&format!("- *[{}]* {}\n", memory.realm_name, preview));
        }
    }

    entry.push_str("\n---\n\n");

    // Read existing content to preserve header
    let existing = if path.exists() {
        std::fs::read_to_string(path)?
    } else {
        String::new()
    };

    // Parse existing entries (split by "\n---\n" after the header)
    let (existing_header, existing_entries) = if existing.contains("# memex8 — Memory Digest") {
        if let Some(divider_pos) = existing.find("\n---\n") {
            let header_part = &existing[..divider_pos + 5];
            let entries_part = &existing[divider_pos + 5..];
            // Split entries by the "\n---\n" separator
            let entries: Vec<&str> = entries_part
                .split("\n---\n")
                .filter(|s| !s.trim().is_empty())
                .collect();
            (header_part.to_string(), entries)
        } else {
            // No separator found — treat entire content as header
            (existing.clone(), vec![])
        }
    } else {
        (String::new(), vec![])
    };

    // Build a fingerprint for dedup: date + stats values
    let _stats_fingerprint = format!(
        "{}-{}-{}-{}-{}",
        report.memories_scanned,
        report.quantized,
        report.realms_updated,
        report.index_optimized,
        report.memories_consolidated
    );

    // Check if the last entry is a duplicate (same date + same stats)
    // This prevents bloating from rapid re-runs with identical results
    let is_duplicate = existing_entries.last().map_or(false, |last| {
        let stats_match = last.contains(&format!("Scanned {} memories", report.memories_scanned))
            && last.contains(&format!("ScalarQuant compressed {} vectors", report.quantized))
            && last.contains(&format!("Updated {} realms", report.realms_updated));
        last.starts_with(&format!("## {}", date)) && stats_match
    });

    let entries_to_keep = if is_duplicate {
        // Skip this entry — it's a duplicate of the last one
        existing_entries
    } else {
        // Add new entry
        let mut all = existing_entries;
        all.push(&entry);
        // Truncate to most recent max_log_entries
        let max = config.max_log_entries as usize;
        if max > 0 && all.len() > max {
            all = all[all.len() - max..].to_vec();
        }
        all
    };

    // Reassemble: header + entries joined by "\n---\n\n"
    let mut content = if existing_header.is_empty() {
        header.to_string()
    } else {
        existing_header
    };

    for (i, e) in entries_to_keep.iter().enumerate() {
        if i > 0 {
            content.push_str("\n---\n\n");
        }
        content.push_str(e);
    }

    std::fs::write(path, &content)?;
    tracing::info!(
        "Digest updated: {} entries (dedup={}, truncated={})",
        entries_to_keep.len(),
        is_duplicate,
        entries_to_keep.len() <= config.max_log_entries as usize
    );
    Ok(entries_to_keep.len())
}
