use crate::storage::qdrant::{MemoryPoint, RealmPoint};

/// Write a MEMEX8.md file to a project directory containing the most important memories.
pub async fn write_memex8_md(
    project_dir: &str,
    memories: &[MemoryPoint],
    realms: &[RealmPoint],
    max_memories: usize,
) -> anyhow::Result<()> {
    let path = std::path::Path::new(project_dir).join("MEMEX8.md");

    let mut md = String::new();
    md.push_str("# MEMEX8 — Memory Context\n");
    md.push_str("<!-- Auto-generated by memex8. Do not edit. Last updated: ");
    md.push_str(&chrono::Utc::now().to_rfc3339());
    md.push_str(" -->\n\n");

    // Active Realms section
    md.push_str("## Active Realms\n");
    for realm in realms {
        md.push_str(&format!("- **{}** ({} memories)", realm.name, realm.memory_count));
        if let Some(desc) = &realm.description {
            md.push_str(&format!(" — {}", desc));
        }
        md.push('\n');
    }
    md.push('\n');

    // Top memories by importance
    md.push_str("## Key Memories\n\n");
    let mut sorted: Vec<&MemoryPoint> = memories.iter().collect();
    sorted.sort_by(|a, b| b.importance.partial_cmp(&a.importance).unwrap_or(std::cmp::Ordering::Equal));

    for memory in sorted.iter().take(max_memories) {
        if let Some(heading) = &memory.heading {
            md.push_str(&format!("### [{}] {}\n", memory.realm_name, heading));
        } else {
            md.push_str(&format!("### [{}]\n", memory.realm_name));
        }

        // Truncate content to first ~200 chars
        let preview: String = memory.content.chars().take(200).collect();
        md.push_str(&format!("> {}...\n\n", preview));
    }

    md.push_str("---\n");
    md.push_str("*Full memory access: `memex8 search \"<query>\"` or http://localhost:8080*\n");

    std::fs::write(&path, md)?;
    tracing::info!("Wrote MEMEX8.md to {}", path.display());
    Ok(())
}

/// Write a DIGEST.md file to the configured path containing realms overview and top memories.
pub async fn write_digest_md(
    config: &crate::config::DigestMdConfig,
    memories: &[MemoryPoint],
    realms: &[RealmPoint],
    _report: &crate::engine::slumber::SlumberReport,
) -> anyhow::Result<usize> {
    if !config.enabled {
        return Ok(0);
    }

    // Expand ~ to HOME
    let path_str = config.path.replace("~", &std::env::var("HOME").unwrap_or_default());
    let path = std::path::Path::new(&path_str);

    // Create parent dir if needed
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut md = String::new();
    md.push_str("# memex8 — Memory Digest\n\n");
    md.push_str("> Auto-generated by memex8 slumber. Do not edit manually.\n\n");

    // Optional realms section
    if config.include_realms && !realms.is_empty() {
        md.push_str("## Realms\n\n");
        for realm in realms {
            md.push_str(&format!(
                "- **{}** ({} memories)",
                realm.name, realm.memory_count
            ));
            if let Some(desc) = &realm.description {
                md.push_str(&format!(" — {}", desc));
            }
            md.push('\n');
        }
        md.push('\n');
    }

    // Top memories by importance
    md.push_str("## Top Memories\n\n");
    let mut sorted: Vec<&MemoryPoint> = memories.iter().collect();
    sorted.sort_by(|a, b| {
        b.importance
            .partial_cmp(&a.importance)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    for memory in sorted.iter().take(config.max_memories as usize) {
        if let Some(heading) = &memory.heading {
            md.push_str(&format!("### [{}] {}\n\n", memory.realm_name, heading));
        } else {
            md.push_str(&format!("### [{}]\n\n", memory.realm_name));
        }

        // Truncate content to first ~200 chars
        let preview: String = memory.content.chars().take(200).collect();
        md.push_str(&format!("> {}...\n\n", preview));
    }

    md.push_str(&format!(
        "\n*Last updated: {}*\n",
        chrono::Utc::now().to_rfc3339()
    ));

    std::fs::write(path, &md)?;
    tracing::info!("Wrote memex8 digest to {}", path.display());
    Ok(1)
}
